import assert from "node:assert/strict";
import { calculateCost } from "../lib/pricing.mjs";
assert.equal(calculateCost(5000, "clinical"), 120);
assert.equal(calculateCost(5000, "transcription"), 60);
assert.equal(calculateCost(1.5, "transcription"), 0.02);
assert.equal(calculateCost(0, "clinical"), 0);
for (const invalid of [-1, NaN, Infinity]) assert.throws(() => calculateCost(invalid, "clinical"), RangeError);
assert.throws(() => calculateCost(10, "unknown"), RangeError);
assert.throws(() => calculateCost(10, "toString"), RangeError);
console.log("Pricing checks passed.");
